<?php
/**
 * @category   Divalto
 * @package    Divalto_extraprice
 * @subpackage view
 */

/**
 * @var $block \Divalto\ExtraPrice\Block\AfterPrice
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="extraprice-container">
        <span class="label"><?= __('Unit Price') ?> : </span><span class="extraprice"><?= $block->getExtraPriceText() ?></span><span><?= __($block->getDisplayExtraPriceTax()) ?></span>
    </div>
    <script type="text/javascript">
        require(['jquery', 'jquery/ui', 'domReady!'], function($) {
            $('body').on('updatePrice', function (e, data) {
                
                var swatchWidget = $('.swatch-opt').data('mage-SwatchRenderer');
                if(swatchWidget) {
                    var options = _.object(_.keys(swatchWidget.optionsMap), {});

                    swatchWidget.element.find('.' + swatchWidget.options.classes.attributeClass + '[option-selected]').each(function () {
                        options[$(this).attr('attribute-id')] = $(this).attr('option-selected');
                    });
                    result = swatchWidget.options.jsonConfig.optionPrices[_.findKey(swatchWidget.options.jsonConfig.index, options)];
                } else {
                    var configurableWidget = $('#product_addtocart_form').data('mage-configurable');
                    var options = {};

                    configurableWidget.element.find(configurableWidget.options.superSelector + ' option:selected').each(function () {
                        if($(this).val()) {
                                options[Number($(this).parent().prop('id').replace('attribute', ''))] = $(this).val();
                        }

                    });

                    var config = configurableWidget.option('spConfig');
                    result = config.optionPrices[_.findKey(config.index, options)];
                
                }

                var extraPriceField = $('.product-info-price .extraprice-container .extraprice');       

                 if(typeof result!=='undefined') {
                    extraPriceField.html(result.divalto_extraprice_text);
                }
            });
        });
    </script>
<?php endif; ?>
